add_book_to_schedule = {"ru": "Добавить книгу в расписание", "en": "Add book to schedule"}
my_schedule = {"ru": "Моё расписание", "en": "My schedule"}
book_advice = {"ru": "Подобрать книги", "en": "Get book advice"}
hello = {"ru": "Привет", "en": "Hello"}
write_book_name = {"ru": "Напишите название книги", "en": "Write the title of the book"}
write_book_genres = {"ru": "Напишите желаемый жанр, если нет предпочитаемого жанра, отправьте \"нет\"", "en": "Write the desired genre, if there is no preferred genre, send \"no\""}
exception_schedule = {"ru": "Ваше расписание пока пустое", "en": "Your schedule is still empty"}
delete_this_essay = {"ru": "Удалить эту запись", "en": "Delete this record"}
check_essay = {"ru": "Посмотреть эссе под номером", "en": "Check essay at position"}
read_essay = {"ru": "Я прочёл под номером", "en": "I read essay at position"}
back = {"ru": "Назад", "en": "Back"}
didnt_write_essay = {"ru": "Вы ещё не написали эссе", "en": "You still didn`t write essay" }
write_essay = {"ru": "Написать эссе", "en": "Write essay"}
rewrite_essay = {"ru": "Переписать эссе", "en": "Rewrite essay"}
changes_cancel = {"ru": "Для отмены изменений напишите", "en": "To cancel changes"}
essay_update = {"ru": "Эссе обновлено и исправлено правописание", "en": "Essay updated and fixed еру spelling"}
fav_books = {"ru": "Напишите любимые книги, если любимых книг нет, отправьте \"нет\"", "en" : "Write your favorite books, if there are no favorite books, send \"no\""}
write_books_authors = {"ru": "Напишите автора(ов) книг", "en": "Write auther(authors)"}
did_you_read = {"ru": "Вы уже прочитали эту книгу?", "en": "Have you already read this book?"}
write_essay_now = {"ru": "Написать эссе", "en": "Write essay"}
book_added = {"ru": "Книга добавлена в расписание", "en": "Book added to schedule"}
yes = {"ru": "Да", "en": "Yes"}
no = {"ru": "Нет", "en": "No"}
author = {"ru": "Автор", "en": "Author"}
book_title = {"ru": "Название книги", "en": "The title of the book"}
download_list = {"ru": "Скачать расписание", "en": "Download schedule"}
